import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: '简介',
    },
    {
      type: 'doc',
      id: 'about',
      label: '关于我们',
    },
    {
      type: 'category',
      label: '代码库',
      link: {
        type: 'generated-index',
        title: '代码库',
        description: '按库名浏览所有漏洞规则',
        slug: '/libraries',
      },
      // This will be auto-generated based on the folder structure
      items: [
        {
          type: 'autogenerated',
          dirName: 'libraries',
        },
      ],
    },
    {
      type: 'category',
      label: '规则分类',
      link: {
        type: 'generated-index',
        title: '规则分类',
        description: '按规则类型浏览所有漏洞规则',
        slug: '/rules',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'rules',
        },
      ],
    },
    {
      type: 'category',
      label: '规则生成工具',
      link: {
        type: 'generated-index',
        title: '规则生成工具',
        description: '用于生成规则的工具',
        slug: '/tools',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'tools',
        },
      ],
    },
  ],
};

export default sidebars;
