from jinja2 import Template

INTRO_TEMPLATE = Template(
    """---
id: intro
title: Intro
sidebar_position: 1
---


# About Vulnerability Rule Library
## Project Introduction
The Vulnerability Rule Library is an open-source project dedicated to helping developers identify and avoid common security vulnerabilities. We collect, organize, and analyze security vulnerability patterns in various programming languages and commonly used libraries, providing corresponding preventive measures and best practices.
## Our Mission
Our mission is to improve security awareness in the software development process by providing a comprehensive and systematic security knowledge base, reducing the occurrence of security vulnerabilities, and contributing to building a more secure software ecosystem.
## Project Features
- **Comprehensive Vulnerability Coverage**: Covers various programming languages and commonly used libraries
- **Practical Rule Guidelines**: Each rule comes with detailed explanations and example code
- **Continuous Updates**: Tracks the latest security research and vulnerability reports
- **Open Source Sharing**: Community contributions and improvements are welcome
## How to Contribute
We welcome various forms of contributions, including but not limited to:
1. Submitting new vulnerability rules
2. Improving the descriptions and examples of existing rules
3. Reporting bugs and suggesting improvements
4. Improving documentation and translations
Please visit our [GitHub repository]({{github_url}}) for more ways to contribute.
## Contact Us
If you have any questions or suggestions, please contact us through the following methods:
- GitHub Issues: [Submit an Issue]({{github_url}}/issues)
- Email: {{email}}
Thank you for your attention and support to the Vulnerability Rule Library!"""
)

API_TEMPLATE = Template(
    """---
---


## API Overview
**{{api_name}}** is an API in **{{lib_name}}**. This rule belongs to the **{{label}}** type. This rule is generated using [{{tool_name}}](../../tools/{{tool_name}}).
## Rule Description

:::tip

{{description}}

:::

:::info

- Tags: **{{label}}**
- Parameter Index: **{{param_index}}**
- CWE Type: **{{cwe_type}}**

:::

## Rule Code
```python
{{code}}
```
"""
)

TOOL_TEMPLATE = Template(
"""---
---


# {{tool_name}} Generated Rules

{{tool_name}} generated {{rule_count}} rules. The following is a list of rules generated by {{tool_name}}. Click on the rule name to view the details.

{% for lib in rules %}
## {{lib}}
{% for name, path in rules[lib] %}
- [{{name}}]({{path}})
{% endfor %}
{% endfor %}
"""
)

TYPE_TEMPLATE = Template(
"""---
---
# {{type_name}}

There are {{rule_count}} rules of type {{type_name}}. The following is a list of rules of type {{type_name}}. Click on the rule name to view the details.

{% for lib in rules %}
## {{lib}}
{% for name, path in rules[lib] %}
- [{{name}}]({{path}})
{% endfor %}
{% endfor %}
"""
)


PROJECT_TEMPLATE = Template(
"""---
---


# {{lib_name}} Rules

{{lib_name}} has {{rule_count}} rules. The following is a list of rules. Click on the rule name to view the details.

{% for name, path in rules %}
- [{{name}}]({{path}})
{% endfor %}
"""
)

API_CATEGORY = {
    "position": 2,
    "label": "Projects",
    "link": {
        "type": "generated-index",
        "title": "Projects",
        "description": "View the rules by projects."
    }
}

TOOLS_CATEGORY = {
    "position": 3,
    "label": "Tools",
    "link": {
        "type": "generated-index",
        "title": "Tools",
        "description": "View the rules by tool."
    }
}

TYPE_CATEGORY = {
    "position": 4,
    "label": "Types",
    "link": {
        "type": "generated-index",
        "title": "Types",
        "description": "View the rules by type."
    }
}

TEMPLATES = {
    "intro": INTRO_TEMPLATE,
    "api": API_TEMPLATE,
    "tool": TOOL_TEMPLATE,
    "type": TYPE_TEMPLATE,
    "project": PROJECT_TEMPLATE
}

CATEGORIES = {
    "api": API_CATEGORY,
    "tool": TOOLS_CATEGORY,
    "type": TYPE_CATEGORY
}